#!/usr/bin/env dart
// ignore_for_file: avoid_print

/// 使用示例
/// `./make.dart build`编译Android、iOS
/// `./make.dart run profile`以profile模式运行

import 'dart:convert';
import 'dart:io';

const appName = 'CustedNG';
const buildDataFilePath = 'lib/res/build_data.dart';
const xcarchivePath = 'build/ios/archive/CustedNG.xcarchive';
const appleXCConfigPath = 'Runner.xcodeproj/project.pbxproj';

var regAppleProjectVer = RegExp(r'CURRENT_PROJECT_VERSION = .+;');
var regAppleMarketVer = RegExp(r'MARKETING_VERSION = .+');

const skslFileSuffix = '.sksl.json';

int build = 0;

final buildFuncs = {
  'ios': flutterBuildIOS,
  'android': flutterBuildAndroid,
};

String buildName;
String buildNumber;

// Future<void> getBuildVersion() async {
//   // final result = await Process.run('git', ['log', '--oneline']);
//   // build = (result.stdout as String)
//   //     .split('\n')
//   //     .where((line) => line.isNotEmpty)
//   //     .length;

//   // 版本号逻辑更改，从绑定 git 到手动指定
//   if (buildName == null || buildNumber == null) {
//     print('Error: version not specified. Usage: ./make.dart build <platform> <versionName+versionCode>');
//     exit(1);
//   }

//   print('Using manual version: $buildName+$buildNumber');
//   build = int.parse(buildNumber) - 756; // 减去初始版本号 756
// }

Future<void> writeStaticConfigFile(
    Map<String, dynamic> data, String className, String path) async {
  final buffer = StringBuffer();
  buffer.writeln('// This file is generated by ./make.dart');
  buffer.writeln('');
  buffer.writeln('class $className {');
  for (var entry in data.entries) {
    final type = entry.value.runtimeType;
    final value = json.encode(entry.value);
    buffer.writeln('  static const $type ${entry.key} = $value;');
  }
  buffer.writeln('}');
  await File(path).writeAsString(buffer.toString());
}

Future<int> getGitModificationCount() async {
  final result =
      await Process.run('git', ['ls-files', '-mo', '--exclude-standard']);
  return (result.stdout as String)
      .split('\n')
      .where((line) => line.isNotEmpty)
      .length;
}

Future<Map<String, dynamic>> getBuildData() async {
  final data = {
    'name': appName,
    'build': build,
    'engine': '2.10.5',
    'buildAt': DateTime.now().toString(),
    'modifications': await getGitModificationCount(),
  };
  return data;
}

String jsonEncodeWithIndent(Map<String, dynamic> json) {
  const encoder = JsonEncoder.withIndent('  ');
  return encoder.convert(json);
}

Future<void> updateBuildData() async {
  print('Updating BuildData...');
  final data = await getBuildData();
  print(jsonEncodeWithIndent(data));
  await writeStaticConfigFile(data, 'BuildData', buildDataFilePath);
}

Future<void> dartFormat() async {
  final result = await Process.run('dart', ['format', '.']);
  print('\n' + result.stdout);
  if (result.exitCode != 0) {
    print(result.stderr);
    exit(1);
  }
}

void flutterRun(String mode) {
  Process.start('flutter', ['run', mode == null ? '' : '--$mode'],
      mode: ProcessStartMode.inheritStdio, runInShell: true);
}

Future<void> flutterBuild(String source, String target, bool isAndroid) async {
  final args = [
    'build',
    isAndroid ? 'apk' : 'ipa',
    '--target-platform=android-arm64',
    '--build-number=$buildNumber',
    '--build-name=$buildName',
    '--bundle-sksl-path=${isAndroid ? 'android' : 'ios'}$skslFileSuffix',
  ];
  if (!isAndroid) args.removeAt(3);
  print('Building with args: ${args.join(' ')}');
  final buildResult = await Process.run('flutter', args, runInShell: true);
  final exitCode = buildResult.exitCode;

  if (exitCode == 0) {
    target = target.replaceFirst('build', build.toString());
    print('Copying from $source to $target');
    if (isAndroid) {
      await File(source).copy(target);
    } else {
      final result = await Process.run('cp', ['-r', source, target]);
      if (result.exitCode != 0) {
        print(result.stderr);
        exit(1);
      }
    }

    print('Done.\n');
  } else {
    print(buildResult.stderr.toString());
    print('\nBuild failed with exit code $exitCode');
    exit(exitCode);
  }
}

Future<void> flutterBuildIOS() async {
  await changeAppleVersion();
  await flutterBuild(
      xcarchivePath, './release/${appName}_build.xcarchive', false);
}

Future<void> flutterBuildAndroid() async {
  await flutterBuild('./build/app/outputs/flutter-apk/app-release.apk',
      './release/${appName}_${buildNumber}_arm64-v8a.apk', true);
  await killJava();
}

Future<void> changeAppleVersion() async {
  for (final path in ['ios', 'macos']) {
    final file = File('$path/$appleXCConfigPath');
    final contents = await file.readAsString();
    final newContents = contents
        .replaceAll(regAppleMarketVer, 'MARKETING_VERSION = 2.0.$build;')
        .replaceAll(regAppleProjectVer, 'CURRENT_PROJECT_VERSION = $build;');
    await file.writeAsString(newContents);
  }
}

Future<void> killJava() async {
  final result = await Process.run('ps', ['-A']);
  final lines = (result.stdout as String).split('\n');
  for (final line in lines) {
    if (line.contains('java')) {
      final pid = line.split(' ')[0];
      print('Killing java process: $pid');
      await Process.run('kill', [pid]);
    }
  }
}

void main(List<String> args) async {
  if (args.isEmpty) {
    print('Usage: ./make.dart <command> [options]');
    exit(1);
  }

  final command = args[0];

  switch (command) {
    case 'run':
      return flutterRun(args.length == 2 ? args[1] : null);

    case 'build':
      if (args.length < 4) {
        print(
            'Usage: ./make.dart build <platform> <versionName> <versionCode>');
        exit(1);
      }

      buildName = args[2];
      buildNumber = args[3];
      build = int.tryParse(buildNumber);

      // await getBuildVersion();
      await dartFormat();
      await updateBuildData();

      final stopwatch = Stopwatch()..start(); // 时间统计
      if (args.length > 1) {
        final platform = args[1];
        if (buildFuncs.containsKey(platform)) {
          await buildFuncs[platform]();
        } else {
          print('Unknown platform: $platform');
          exit(1);
        }
      } else {
        for (final func in buildFuncs.values) {
          await func(); // 未指定平台参数则依次执行编译
        }
      }

      print('Build finished in ${stopwatch.elapsed}');
      return;

    case 'update-build':
      return updateBuildData();

    default:
      print('Unsupported command: $command');
      return;
  }
}
