// This file is generated by ./make.dart

class BuildData {
  static const String name = "CustedNG";
  static const int build = 756;
  static const String engine = "2.10.5";
  static const String buildAt = "2025-08-27 16:01:22.261356";
  static const int modifications = 14;
}
