// This file is generated by ./make.dart

class BuildData {
  static const String name = "CustedNG";
  static const int build = 757;
  static const String engine = "2.10.5";
  static const String buildAt = "2025-09-03 20:06:45.356384";
  static const int modifications = 3;
}
